#!/bin/bash
####################################################################
# Prey Network Module Lang File - by Dan Sellberg (dan@dkcp.com)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

STRING_GET_IP=" -- Hämtar publik IP-adress ..."
STRING_GET_LAN_IP=" -- Hämtar IP-adress för privat LAN ..."
STRING_GET_WIFI=" -- Hämtar information om trådlösa nätverk ..."
STRING_TRACE=" -- Spårar vår fullständiga väg till internet ..."
