#!/bin/bash
####################################################################
# Prey Lock Mac Functions - by Tomas Pollak (bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

lock__executable="$module_platform_path/prey-lock.app/Contents/MacOS/prey-lock"
