#!/bin/bash
####################################################################
# Prey Retrieve Module - by Tomas Pollak (bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

perform_backup
