#!/bin/bash
####################################################################
# Prey System Module Lang File
# URL: http://preyproject.com
# License: GPLv3
####################################################################

STRING_GET_CPU_INFO=" -- Hämtar processorinformation ..."
STRING_GET_MEMORY_INFO=" -- Hämtar minnesinformation..."
STRING_GET_HDD_INFO=" -- Hämtar hårddiskinformation..."
