#!/bin/bash
####################################################################
# Prey Geo Module Windows Functions - by Tomas Pollak (bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

get_wifi_access_points() {

	if [ -z "$wifi_info" ]; then
		get_wifi_info
	fi
	wifi_points=`echo "$wifi_info" | tr -d '\n'`

}
