#!/bin/bash
####################################################################
# Prey Webcam Module Linux Functions - by Tomas Pollak (bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

tmp_picture="$tmpdir/picture.jpeg"

take_picture() {

	# do we have streamer installed ?
	local streamer=`which streamer`
	if [ -n "$streamer" ]; then

		$streamer -o "$tmp_picture" &> /dev/null # streamer necesita que sea JPEG (con la E) para detectar el formato

		if [ -f "$tmp_picture" ]; then

			mv "$tmp_picture" "$picture" > /dev/null

		else # by Vanscot, http://www.hometown.cl/ --> some webcams are unable to take JPGs so we grab a PPM

			$streamer -o "$tmpdir/picture.ppm" &> /dev/null
			if [ -f "$tmpdir/picture.ppm" ]; then

				local convert=`which convert`
				if [ -n "$convert" ]; then # lets convert it to JPG if we have imagemagick installed
					$convert "$tmpdir/picture.ppm" $picture > /dev/null
				else # lets just send it as a PPM
					picture="$tmpdir/picture.ppm"
				fi

			fi

		fi

	fi

}

capture_video() {

	# we should already know if we do have streamer
	if [ -n "$streamer" ]; then

		local frames=$(( $video_capture_time * $frames_per_second ))
		$streamer -o $video -f yuv2 -F stereo -r $frames_per_second -t $frames

	fi

}
