#!/bin/bash
####################################################################
# Prey Network Module Mac Functions - by Tomas Pollak (bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

get_mac_address() {
	# this one is actually the gateway's mac address!
	# mac_address=`arp -n $gateway_ip | cut -f4 -d' '`
	mac_address=`/sbin/ifconfig | grep ether | sed -e 's/ether //g' -e 's/^[^a-z0-9]//g' | head -1`
}
