#!/bin/bash
####################################################################
# Prey Network Module Mac Functions - by Tomas Pollak (bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

get_active_connections() {
	active_connections=$(/usr/sbin/netstat -p tcp -a)
}
