#!/bin/bash
####################################################################
# Prey Webcam Module Lang File - by Tomas Pollak (http://bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

STRING_TAKE_PICTURE=" -- Prise de photo de l'imposteur..."
STRING_CAPTURE_VIDEO=" -- Enregistrement de $video_capture_time secondes de video..."
