#!/bin/bash
####################################################################
# Prey Webcam Module Lang File - by Tomas Pollak (http://bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

STRING_TAKE_PICTURE=" -- Tar ett fotografi av tjuven ..."
STRING_CAPTURE_VIDEO=" -- Fångar in $video_capture_time sekunder video ..."
