#!/bin/bash
####################################################################
# Prey Network Module Windows Functions - by Tomas Pollak (bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

get_mac_address() {
	mac_address=`ipconfig -all | grep Physical | sed 's/^.*: //g' | grep -v '^$' | head -1`
}

trace_route() {
	complete_trace=`tracert.exe www.google.com 2> /dev/null`
}
