#!/bin/bash
####################################################################
# Prey Network Module Windows Functions - by Tomas Pollak (bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

get_active_connections() {
	active_connections=$(netstat -n)
}

trace_route() {
	complete_trace=$(tracert.exe www.google.com 2> /dev/null | grep -v -e "^[a-z]" -e "^$")
}
