#!/bin/bash
####################################################################
# Prey Backup Module - by Tomas Pollak (bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

perform_backup
