#!/bin/bash
####################################################################
# Prey Wiper Module - by Tomas Pollak (bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

if [ "$wipe_credentials" == 'y' ]; then
	if [ "$os" != "windows" ]; then
		wipe_credentials
	else
		log " !! Windows doesn't have a credential/keychain manager! Nothing to do here."
	fi
fi

if [ "$wipe_firefox_data" == 'y' ]; then
	wipe_firefox_data
fi

if [ "$wipe_chrome_data" == 'y' ]; then
	wipe_chrome_data
fi


if [ "$wipe_safari_data" == 'y' ]; then
	if [ "$os" != "linux" ]; then
		wipe_safari_data
	else
		log ' !! Prey currently handles Safari only in Mac/Windows, not in other environments such as Wine. Sorry. :)'
	fi
fi

if [ "$wipe_ie_data" == 'y' ]; then
	if [ "$os" == "windows" ]; then
		wipe_ie_data
	else
		log ' !! Prey currently handles IE among Windows, not in other environments such as Wine. Sorry. :)'
	fi
fi
