#!/bin/bash
####################################################################
# Prey Network Module Core Functions - by Tomas Pollak (bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

get_public_ip() {
	public_ip=`$getter checkip.dyndns.org|sed -e 's/.*Current IP Address: //' -e 's/<.*$//'`
}

get_internal_ip() {
	internal_ip=`/sbin/ifconfig 2> /dev/null | grep "inet " | grep -v "127.0.0.1" | awk '{ print $2}' | sed 's/addr://' | head -1`
}

trace_route() {
	traceroute=`which traceroute`
	if [ -n "$traceroute" ]; then
		complete_trace=`$traceroute -q1 www.google.com 2>&1`
	fi
}
