#!/bin/bash
####################################################################
# Prey Network Module Core Functions - by Tomas Pollak (bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

get_public_ip() {
	public_ip=$(getter --connect-timeout 3 checkip.dyndns.org | sed 's/[^0-9\.]//g')
}

# for linux and mac
trace_route() {
	traceroute=$(which traceroute)
	if [ -n "$traceroute" ]; then
		complete_trace=$($traceroute -q1 www.google.com 2>&1 | grep -v -e "^[a-z]" -e "^$")
	fi
}
