#!/bin/bash
####################################################################
# Prey Network Module - by Tomas Pollak (bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

log "$STRING_GET_IP"
get_public_ip
add_trace public_ip $public_ip

log "$STRING_GET_LAN_IP"
internal_ip=$(get_ip_address | head -1)
add_trace internal_ip $internal_ip

log " -- Getting gateway IP address..."
gateway_ip=$(get_gateway_ip | head -1)
add_trace gateway_ip $gateway_ip

if [ "$network__get_active_connections" == 'y' ]; then
	log "$STRING_ACTIVE_CONNECTIONS"
	get_active_connections
	add_trace active_connections "$active_connections"
fi

if [ "$network__get_nearby_wifi_hotspots" == 'y' ]; then
	log "$STRING_GET_WIFI"
	[ -z "$wifi_info" ] && get_wifi_info
	[ -n "$wifi_info" ] && add_trace wifi_info "$wifi_info"
fi

if [ "$network__trace_route" == 'y' ]; then
	log "$STRING_TRACE"
	trace_route
	add_trace complete_trace "$complete_trace"
fi
