#!/bin/bash
####################################################################
# Prey Alert Module Windows Functions - by Tomas Pollak (bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

# never tested!
change_wallpaper() {
	# reg add "hkcu\control panel\desktop" /v wallpaper /t REG_SZ /d "$wallpaper" /f
	# RUNDLL32.EXE user32.dll,UpdatePerUserSystemParameters
	echo ' !! Wallpaper switching still being tested on Windows!'
}

alert_user() {
	run_as_current_user "\"$module_platform_path/msgbox.exe\" \"$alert__alert_message\"" 
}


say_message(){
	echo " -- Don't know which text-to-speech software to use!"
}
