#!/bin/bash
####################################################################
# Prey Secure Module Core Functions - by Tomas Pollak (bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

delete_credentials() {
	if [ -d "$users_path" ]; then
		for user in `find "$users_path" -maxdepth 1 -mindepth 1 -type d`; do
			if [ -d "$user/$credentials_path" ]; then
				log " -- Deleting $user's stored credentials..."
				rm -Rf "$user/$credentials_path" 2> /dev/null
			fi
		done
	fi
}

# receives $1 => path, $2 => name of program
# example: delete_data_from 'safari' $safari_data_path
delete_data_from() {
	if [ "$terminate_if_running" == "y" ]; then
		kill_process $1
	fi
	if [ -d "$users_path" ]; then
		for user in `find "$users_path" -maxdepth 1 -mindepth 1 -type d`; do
			if [ -d "$user/$2" ]; then
				log " -- Deleting $user's data from $1..."
				rm -Rf "$user/$2" 2> /dev/null
			fi
		done
	fi
}

# in this case we dont want to delete the whole profile folder,
# as there may be important stuff that we may want to access later (emails)
hide_data_from(){
	if [ "$terminate_if_running" == "y" ]; then
		kill_process $1
	fi
	if [ -d "$users_path" ]; then
		for user in `find "$users_path" -maxdepth 1 -mindepth 1 -type d`; do
			if [ -d "$user/$2" ]; then
				log " -- Hiding $user's data from $1..."
				mv "$user/$2" "$user/$2.backup" 2> /dev/null
			fi
		done
	fi
}
