#!/bin/bash
####################################################################
# Prey System Module - by Carlos Yaconi H.
# URL: http://preyproject.com
# License: GPLv3
####################################################################

log " -- Scanning current system's hardware..."
scan_system_hardware

log ' -- Sending updated data...'
send_updated_hardware_data

#get_os_info
#log  "OS Version: $os_version"
#log "Kernel Version: $kernel_version"

#get_cpu_info
#log "CPU info: $cpu_info"

#get_memory_info
#log "Memory info: $mem_info"
#log "Memory Total: $mem_total"

#get_system_ids
#log "Serial number: $serial_number"
#log "UUID: $hw_UUID"

#get_hdd_info
#log "HDD info: $hdd_info"

#add_trace cpu_name $cpu_name
#add_trace cpu_speed $cpu_speed
#add_trace cpu_number $cpu_number
#add_trace cpu_cores $cpu_cores
