#!/bin/bash
####################################################################
# PREY Webcam Module Mac Functions - by Tomas Pollak (bootlog.org)
# URL : http://preyproject.com
# License: GPLv3
####################################################################

take_picture() {

	if [ "`whoami`" == "root" ]; then
		launchctl bsexec $logged_pid $module_path/lib/isightcapture $picture 2> /dev/null
	else
		$module_path/lib/isightcapture $picture 2> /dev/null
	fi

}

capture_video() {

	echo ' !! Feature still in development!'

}
