#!/bin/bash
####################################################################
# Prey Geo Module Windows Functions - by Tomas Pollak (bootlog.org)
# URL : http://preyproject.com
# License: GPLv3
####################################################################

function get_wifi_access_points {
	if [ `is_net_framework_installed $required_net_version` == 1 ]; then
		echo autowc -list
	else
		echo " !! .NET framework version $required_net_version or newer not installed! Cannot obtain geo information."
	fi
}
