#!/bin/bash
####################################################################
# Prey Geo Module Windows Functions - by Tomas Pollak (bootlog.org)
# URL : http://preyproject.com
# License: GPLv3
####################################################################

get_wifi_access_points() {

	if [ "`is_net_framework_installed`" == 1 ]; then
		wifi_points=`autowc -list`
	else
		echo " !! .NET framework version $required_net_version or newer not installed! Cannot obtain geo information."
	fi

}
