#!/bin/bash
####################################################################
# Prey Alarm Module Windows Functions
# URL : http://preyproject.com
# License: GPLv3
####################################################################

sound_alarm() {
	local player="$module_platform_path/mpg123.exe"
	run_as_current_user "\"$player\" \"$alarm__sound_file\"" &> /dev/null &
}
