#!/bin/bash
####################################################################
# Prey System Module Windows Functions - by Carlos Yaconi H.
# URL: http://preyproject.com
# License: GPLv3
####################################################################

##This function MUST be called first, since it grabs windows information to be used by the other functions
get_os_info(){
	win_info=`systeminfo`
	os_version=`echo "$win_info" | grep "OS Name" | sed 's/.*: *\(.*\)/\1/'`
	kernel_version=`echo "$win_info" | grep "^OS Version" | sed 's/.*: *\(.*\)/\1/'`
}       

get_cpu_info(){
	#cpu_name - cpu_speed - cpu_cores  
	cpu_name=`echo "$win_info" | grep "Processor(s)" -A1 | tail -1 | sed 's/.*\[.*\]: \(.*\)/\1/'`
	cpu_speed=`echo "$win_info"  | grep "Processor(s)" -A1 | tail -1 | sed 's/.*\[.*\]:.*~\(.*\)/\1/'`
	cpu_number=`echo "$win_info" | grep "Processor(s)" | sed 's/.*: *\([0-9]\) .*/\1/'`
	
	cpu_info="1_name=${cpu_name}#1_speed=${cpu_speed}#1_cores=${cpu_number}__#"
}

get_memory_info(){
	#Need to use wmi to grab more ram info.	
	total_mem=`echo "$win_info"	| grep "Total Physical Memory" | sed 's/.*: \(.*\)/\1/'`
	
	mem_info="1_size=${total_mem}#1_type=0#1_speed=0__#"
	
}

get_hdd_info(){
  hdd_full_info=`"$module_platform_path/hddinfo.exe"`
  hdd_info=`echo "$hdd_full_info"  | awk 'BEGIN { 
	ORS = "#"}
	/Disk/ { UNIT=$2}
	/Capacity/ { print UNIT"_size="$2" "$3}
	/Model: / { print UNIT"_model="substr ($0, 9)}
	/Serial: / { print UNIT"_serial="substr ($0, 10)}
	/Firmware: / { print UNIT"_fimware="substr ($0, 12)"__"}'`

} 


get_system_ids(){
	serial_number=`wmic baseboard get serialnumber | awk 'NR==2 {print $1}'`
	hw_UUID=`wmic path win32_computersystemproduct get uuid | awk 'NR==2 {print $1}'`
}
