#!/bin/bash
####################################################################
# Prey System Module Windows Functions - by Carlos Yaconi H.
# URL: http://preyproject.com
# License: GPLv3
####################################################################

wmic_call(){
	echo "$1" | wmic 2> /dev/null | grep -v 'wmic:' | grep -v "^$" | tail -1
	rm -f "$base_path/TempWmicBatchFile.bat" &> /dev/null
}

#get_os_info(){
#	os_version=$(wmic_call "os get version")
#}

get_system_ids(){
	system__serial_number=$(wmic_call "bios get serialnumber")
	# serial_number=$(wmic_call "path win32_computersystemproduct get identifyingnumber" | awk 'NR==2 {print $1}')
	system__uuid=$(wmic_call "path win32_computersystemproduct get uuid")
}

get_mb_info(){
	system__mb_vendor=$(wmic_call "baseboard get manufacturer")
	system__mb_serial=$(wmic_call "baseboard get serialnumber")
	system__mb_model=$(wmic_call "baseboard get product")
	system__mb_version=$(wmic_call "baseboard get version")
}

get_bios_info(){
	system__bios_vendor=$(wmic_call "bios get Manufacturer")
	system__bios_version=$(wmic_call "bios get SMBIOSBIOSVersion")
}

get_cpu_info(){
	system__cpu_model=$(wmic_call "cpu get name")
	system__cpu_speed=$(wmic_call "cpu get MaxClockSpeed")
	system__cpu_cores=$(wmic_call "cpu get NumberOfCores")
	# cpu_info="1_name=${cpu_name}#1_speed=${cpu_speed}#1_cores=${cpu_cores}__#"
}

get_memory_info(){
	local ram_in_bytes=$(wmic_call "os get TotalVisibleMemorySize")
	system__ram_size=$(($ram_in_bytes/1024))
	system__ram_modules=$(cscript "$module_platform_path\\ramcheck.vbs" | grep "Bank Label" | wc -l | sed "s/ //g")
}

get_network_interfaces(){

	local nic_list=$(echo "nic list full" | wmic 2> /dev/null | grep "MACAddress=." -A4)

	local id=0
	while read line; do

		local key=$(echo "$line" | cut -d '=' -f1)
		local value=$(echo "$line" | cut -d '=' -f2)

		if [ "$key" == "MACAddress" ]; then

			id=$(($id+1))

			local mac_address="$value"
			store_network_interface_value "nic_${id}" "mac_address" "$mac_address"

			local ip_address=$(get_ip_address "$mac_address")
			local netmask=$(get_netmask "$mac_address")
			local gateway_ip=$(get_gateway_ip "$mac_address")

			store_network_interface_value "nic_${id}" "ip_address" "$ip_address"
			store_network_interface_value "nic_${id}" "netmask" "$netmask"
			store_network_interface_value "nic_${id}" "gateway_ip" "$gateway_ip"

		elif [ "$key" == "Manufacturer" ]; then
			store_network_interface_value "nic_${id}" "vendor" "$value"
		elif [ "$key" == "Name" ]; then
			store_network_interface_value "nic_${id}" "model" "$value"

			if [ -n "$(echo "$value" | egrep -i 'wireless|wifi|802.11' 2> /dev/null" ]; then
				store_network_interface_value "nic_${id}" "interface_type" "Wireless"
			fi

		fi

	done <<< "$nic_list"
}

get_storage_devices(){
	log " -- Storage devices getter still in the works!"
}
