#!/bin/bash
####################################################################
# Prey Wiper Module Windows Functions - by Tomas Pollak (bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

# XP -> C:\Documents and Settings\<user>\Local Settings\Application Data\
# Vista -> C:\Users\<username>\AppData\Local\

if [ -d "C:\Users" ]; then # vista and up

	user_path="C:\Users"
	data_path="\AppData\Local"

else # xp and 2000

	user_path="C:\Documents\ and\ Settings"
	data_path="\Application\ Data"

fi

# this is all untested stuff!

function wipe_firefox_data {
	for user in `find "$user_path" -maxdepth 1 -mindepth 1 -type d`; do
		rm -Rf "${user}${data_path}\Mozilla\Firefox" 2> /dev/null
	done
	if [ "$terminate_running_browser" == "y" ]; then
		taskkill /F /IM firefox 2> /dev/null
	fi
}

function wipe_chrome_data {
	for user in `find "$user_path" -maxdepth 1 -mindepth 1 -type d`; do
		rm -Rf "${user}${data_path}\Google\Chrome" 2> /dev/null
	done
	if [ "$terminate_running_browser" == "y" ]; then
		taskkill /F /IM chrome 2> /dev/null
	fi
}

function wipe_safari_data {
	for user in `find "$user_path" -maxdepth 1 -mindepth 1 -type d`; do
		rm -Rf "${user}${data_path}\Apple\ Computer\Safari" 2> /dev/null
	done
	if [ "$terminate_running_browser" == "y" ]; then
		taskkill /F /IM safari 2> /dev/null
	fi
}

function wipe_ie_data{
	# RunDll32.exe InetCpl.cpl,ClearMyTracksByProcess 32
	# this above deletes all, but well do it by parts so we have more control
	wipe_ie_passwords
	wipe_ie_form_data
	wipe_ie_temporary_internet_files
	wipe_ie_cookies
	wipe_ie_history
	if [ "$terminate_running_browser" == "y" ]; then
		taskkill /F /IM iexplore 2> /dev/null
	fi
}

function wipe_ie_passwords {
	RunDll32.exe InetCpl.cpl,ClearMyTracksByProcess 32
}

function wipe_ie_form_data {
	Rundll32.exe inetcpl.cpl,ClearMyTracksByProcess 16
}

function wipe_ie_temporary_internet_files {
	RunDll32.exe InetCpl.cpl,ClearMyTracksByProcess 8
}

function wipe_ie_cookies {
	RunDll32.exe InetCpl.cpl,ClearMyTracksByProcess 2
}

function wipe_ie_history {
	RunDll32.exe InetCpl.cpl,ClearMyTracksByProcess 1
}
