#!/bin/bash
####################################################################
# PREY Wiper Module Configuration File - by Tomas Pollak (bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

# whether to destroy the keychains/keyrings that holds all the different
# passwords in your system. recommended if you do use them.
wipe__delete_credentials='n'

# delete all user profiles for firefox
wipe__delete_firefox_data='n'

# delete all user profiles for chrome
wipe__delete_chrome_data='n'

# delete all user profiles for safari (mac & windows only)
wipe__delete_safari_data='n'

# delete everything for running user in IE (windows only)
wipe__delete_ie_data='n'

# should we make sure the browser were wiping the user data isn't running?
wipe__terminate_running_browser='y'
