#!/bin/bash
####################################################################
# Prey Geo Module - by Tomas Pollak (bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

get_wifi_access_points

if [ -n "$wifi_points" ]; then

	get_current_location
	parse_location_response

fi

if [ -n "$current_lat" ]; then

	add_trace 'lat' $current_lat
	add_trace 'lng' $current_lng
	# add_trace 'address' "$current_address"
	add_trace 'wifi' "$wifi_points"
	add_trace 'full' "$current_location_json"

fi
