#!/bin/bash
####################################################################
# Prey Webcam Module Mac Functions - by Tomas Pollak (bootlog.org)
# URL : http://preyproject.com
# License: GPLv3
####################################################################

take_picture() {

	if [ "`whoami`" == "root" ]; then
		launchctl bsexec $logged_pid "$module_platform_path/isightcapture" "$webcam__picture" 2> /dev/null
	else
		"$module_platform_path/isightcapture" "$webcam__picture" 2> /dev/null
	fi

}

capture_video() {

	log ' !! Feature still in development!'

}
