#!/bin/bash
####################################################################
# Prey Webcam Module Mac Functions - by Tomas Pollak (bootlog.org)
# URL : http://preyproject.com
# License: GPLv3
####################################################################

take_picture() {

	run_as_current_user "$module_platform_path/imagesnap -w 1 $webcam__picture" &> /dev/null

}

capture_video() {

	log ' !! Feature still in development!'

}
