#!/bin/bash
####################################################################
# Prey Webcam Module Windows Functions - by Tomas Pollak (bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

take_picture() {

	if [ ! -f "$WINDIR\system32\msvbvm50.dll" ]; then
		if [ ! -f "$platform_path\bin\msvbvm50.dll" ]; then
			echo ' ** Fetching necessary DLL for Webcam capture to work... (about 1 MB)'
			wget http://examples.oreilly.com/error/CDROM/MsLibs/MSVBVM50.DLL -O "$platform_path/bin/msvbvm50.dll" 2> /dev/null
		fi
	fi

	# we could add dimensions to the image (-w 640 -h 480)
	"$module_platform_path/snapshot.exe" -q 100 "$webcam__picture"
}

capture_video() {

	echo ' !! Video capture still in development!'

}
