#!/bin/bash
####################################################################
# PREY Alert Module Core Functions - by Tomas Pollak (bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

# Added by Rodrigo Linfati (linfati.cl)
put_email_on_wallpaper() {
	convert=`which convert`
	if [ -n "$convert" ]; then
		cp $wallpaper $wallpaper.orig
		echo convert -pointsize 24 -draw \'text 450 525 $mail_to\' $wallpaper.orig $wallpaper | sh
	else
		echo ' !! You need to install Imagemagick so that Prey can add your email automatically to the wallpaper image.'
	fi
}
