#!/bin/bash
####################################################################
# Prey Alarm Module Mac Functions
# URL : http://preyproject.com
# License: GPLv3
####################################################################

sound_alarm() {
	local player="afplay"
	osascript -e "set Volume 10"
	$player $alarm__sound_file &> /dev/null &
}
