#!/bin/bash
####################################################################
# Prey Alarm Module Core Functions - by Tomas Pollak (bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

sound_alarm() {
	player="mpg123"
	if [ "$os" == "windows" ]; then
		player="$module_platform_path/$player"
	elif [ "$os" == "darwin" ]; then
		player=afplay
	fi
	# $player -q $alarm_sound --loop $alarm_loops &> /dev/null &
	$player $alarm__sound &> /dev/null &
}
