#!/bin/bash
####################################################################
# Prey Alarm Module - by Tomas Pollak (bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

echo " -- Sounding $alarm__sound!"
sound_alarm
