#!/bin/bash
####################################################################
# Prey Alarm Module - by Tomas Pollak (bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

log " -- Sounding $alarm__sound!"
alarm__sound_file="${module_path}/lib/${alarm__sound}.mp3"
sound_alarm
