#!/bin/bash
####################################################################
# PREY Wiper Module Linux Functions - by Tomas Pollak (bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

credentials_path=".gnome2/keyrings"
firefox_path=".mozilla"
thunderbird_path=".thunderbird"

if [ -d "/home/$logged_user/.config/google-chrome" ]; then
	chrome_path=".config/google-chrome"
elif [ -d "/home/$logged_user/.config/chromium" ]; then
	chrome_path=".config/chromium"
fi
