#!/bin/bash
####################################################################
# PREY Alert Module Configuration File - by Tomas Pollak (bootlog.org)
# URL : http://preyproject.com
# License: GPLv3
####################################################################

# alert the user with a message, y or n
alert__message='This is a stolen computer, and has been marked by Prey. Contact us immediately at http://preyproject.com to clarify the situation. YOU HAVE BEEN WARNED!'

# change wallpaper to alert nearby users -- EXPERIMENTAL!
alert__change_wallpaper='n'
alert__wallpaper="$module_path/lib/prey-wallpaper-$lang.png"
