#!/bin/bash
####################################################################
# Prey System Module Mac Functions - by Carlos Yaconi H.
# URL: http://preyproject.com
# License: GPLv3
####################################################################
get_os_info(){
	os_info=`system_profiler SPSoftwareDataType`
	os_version=`echo "$os_info" | grep "System Version" | sed 's/.*: \(.*\)/\1/'`
	kernel_version=`echo "$os_info" | grep "Kernel Version" | sed 's/.*: \(.*\)/\1/'`
	
}       
get_cpu_info(){
	#cpu_name - cpu_speed - cpu_number - cpu_cores  
	cpu_info=`system_profiler SPHardwareDataType`
	cpu_name=`echo "$cpu_info" | grep "Processor Name" | sed 's/.*: \(.*\)/\1/'`
	cpu_speed=`echo "$cpu_info"  | grep "Processor Speed" | sed 's/.*: \(.*\)/\1/'`
	#cpu_number=`echo "$cpu_info" | grep "Number Of Processors" | sed 's/.*: \(.*\)/\1/'`
	cpu_cores=`echo "$cpu_info" | grep "Total Number Of Cores" | sed 's/.*: \(.*\)/\1/'` 
	
	cpu_info="1_name=${cpu_name}#1_speed=${cpu_speed}#1_cores=${cpu_number}__#"
}

get_memory_info(){
	mem_full_info=`system_profiler SPMemoryDataType` 
	mem_info=`echo "$mem_full_info"	| awk 'BEGIN { 
		BANK_NUM = 0
		ORS = "#"}

		/BANK/ { BANK_NUM+=1  }
		/Size: /{	print BANK_NUM"_size="$2$3 }
		/Type: /{	print BANK_NUM"_type="$2 }
		/Speed: /{	print BANK_NUM"_speed="$2$3"__" }'`
}

get_hdd_info(){
	hdd_info=`system_profiler SPSerialATADataType | awk 'BEGIN { 
	UNIT = 0
	ORS = "#"}

	/Vendor/ { UNIT+=1 ; cap=0}
	/Model: /{ print UNIT"_model="$2" "$3 }
	/Serial Number: /{ print UNIT"_serial=$3 }
	/Revision: /{ print UNIT"_firmware=$3 }
	/Capacity: / && cap==0 { print UNIT"_size="$2$3 ; cap=1}'`

} 

get_system_ids(){
	hw_info=`system_profiler SPHardwareDataType`
	serial_number=`echo "$hw_info" | grep "Serial Number" | sed 's/.*: \(.*\)/\1/'`
	hw_UUID=`echo "$uuid_info"  | grep "UUID" | sed 's/.*: \(.*\)/\1/'`
}
